### PR TITLE
RDFTermFactory interface. Fixes #26

### LINKED ISSUE #26: Add RDFTermFactory
Should we add an RDFTermFactory interface with methods to map Java Types to RDF (particularly XML Schema) Literals, and allow creation of IRIs and BlankNodes?

### PR DESCRIPTION
**Pull request by ansell**
Initial concept for an RDFTermFactory, based on Sesame ValueFactory with changes to fit RDF-1.1 terminology and new methods.

### CODE REVIEW

**Comment by ansell** [comment]
It could be useful to drop the older date API. 

The new API has TemporalAccessor and TemporalAmount as its main top interfaces, but they don't recommend that people heavily reuse those in their APIs. We could go for LocalDate/LocalDateTime/LocalTime/ZonedDateTime/Year/YearMonth/Duration/Period. Alternatively we could specify TemporalAccessor and TemporalAmount to be compatible with all known implementations and throw exceptions if the actual date/period/duration is not able to be mapped to XML Schema Datatypes, based on using TemporalAccessor.isSupported to determine whether a field is set or not.

**Comment by stain** [comment]
See also my [RDFTermFactory](https://github.com/stain/commons-rdf/blob/tests/src/test/java/com/github/commonsrdf/api/RDFTermFactory.java) of #42 as well

I think this should be promoted from the test to `src/main/java` - but did not put it like that in the #42 pull request to avoid any controversy.

If we do, then it should also include javadocs about local scope and conversion similar to that of #48.

**Comment by stain** [comment]
+1 to drop the older API. [LocalDateTime.toString](http://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html#toString--) already is documented to give the right ISO 8601 output.

**Comment by ansell** [comment]
Closed, implemented by @stain in another pull request

**Comment by stain** [comment]
Well, #52 didn't implement any of the createLiteral(JavaThing) that were in
this request - is that what we agree on to drop those? (I'm +1 for that)

On 26 January 2015 at 05:21, Peter Ansell <notifications@github.com> wrote:

> Closed #30 <https://github.com/commons-rdf/commons-rdf/pull/30>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commons-rdf/commons-rdf/pull/30#event-224442144>.
>



-- 
Stian Soiland-Reyes, eScience Lab
School of Computer Science
The University of Manchester
http://soiland-reyes.com/stian/work/    http://orcid.org/0000-0001-9842-9718

**Comment by ansell** [comment]
I will open a new pull request for those extensions. It would definitely be useful to map typical Java types using RDFTermFactory.

**Pull request closed without merging**
